### ISSUE TITLE
Add our publication works 

### ISSUE THREAD

**Issue by mnipavan** [seeder-research/fantasi#1]
This repository contains the code for reproducing the results in the following papers. If you use our code in your research, please cite:

Venkata Pavan Kumar Miriyala, Xuanyao Fong, Gengchiau Liang, "FANTASI: A Novel Devices-to-Circuits Simulation Framework for Fast Estimation of Write Error Rates in Spintronics", 2018 International Conference on Simulation of Semiconductor Processes and Devices (SISPAD), Austin, TX, pp. 53-57, 2018.

Venkata Pavan Kumar Miriyala, Xuanyao Fong, Gengchiau Liang, “Influence of Size and Shape on the Performance of VCMA-Based MTJs”, IEEE Transactions on Electron Devices, pg. 944-949, 66, 2, 2019.

**Comment by xfong** [comment]
Issue(#2)
